<<<<<<< HEAD
20190607-14:13:03: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-14:13:03: Created session: FIX.4.4:001/001B27->EXC
20190607-14:13:03: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-14:13:03: MINA session created: local=/172.16.0.229:49446, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-14:13:04: Initiated logon request
20190607-14:13:04: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-14:13:04: Received logon
20190607-14:13:07: java.lang.NullPointerException
=======
20190607-12:29:11: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-12:29:11: Session state is not current; resetting FIX.4.4:001/001B27->EXC
20190607-12:29:11: Created session: FIX.4.4:001/001B27->EXC
20190607-12:29:12: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-12:29:12: MINA session created: local=/172.16.1.1:64435, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-12:29:13: Initiated logon request
20190607-12:29:13: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-12:29:13: Received logon
20190607-12:30:59: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-12:30:59: Created session: FIX.4.4:001/001B27->EXC
20190607-12:31:00: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-12:31:00: MINA session created: local=/172.16.1.1:64518, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-12:31:01: Initiated logon request
20190607-12:31:01: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-12:31:01: Received logon
20190607-12:37:17: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-12:37:17: Created session: FIX.4.4:001/001B27->EXC
20190607-12:37:17: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-12:37:17: MINA session created: local=/172.16.1.1:64640, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-12:37:18: Initiated logon request
20190607-12:37:18: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-12:37:18: Received logon
20190607-12:37:20: java.lang.NullPointerException
>>>>>>> 069492ed1c47821f77e483ed6a9d34242fbb67bb
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
<<<<<<< HEAD
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:347)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:214)
=======
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:355)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:212)
>>>>>>> 069492ed1c47821f77e483ed6a9d34242fbb67bb
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
<<<<<<< HEAD
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:347)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:214)
=======
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:355)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:212)
>>>>>>> 069492ed1c47821f77e483ed6a9d34242fbb67bb
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
<<<<<<< HEAD
	at java.lang.Thread.run(Thread.java:748)

20190607-14:13:07: MsgSeqNum too high, expecting 2 but received 3: 8=FIX.4.49=19235=R34=349=EXC52=20190607-14:13:07.26256=001131=20190607-000000000012.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=185
20190607-14:13:07: Enqueued at pos 3: 8=FIX.4.49=19235=R34=349=EXC52=20190607-14:13:07.26256=001131=20190607-000000000012.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=185
20190607-14:13:07: Sent ResendRequest FROM: 2 TO: 2
20190607-14:13:07: ResendRequest for messages FROM 2 TO 2 has been satisfied.
20190607-14:13:07: java.lang.NullPointerException
=======
	at java.lang.Thread.run(Unknown Source)

20190607-12:37:20: MsgSeqNum too high, expecting 2 but received 3: 8=FIX.4.49=19235=R34=349=EXC52=20190607-12:37:21.17456=001131=20190607-000000000001.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=185
20190607-12:37:20: Enqueued at pos 3: 8=FIX.4.49=19235=R34=349=EXC52=20190607-12:37:21.17456=001131=20190607-000000000001.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=185
20190607-12:37:20: Sent ResendRequest FROM: 2 TO: 2
20190607-12:37:20: ResendRequest for messages FROM 2 TO 2 has been satisfied.
20190607-12:37:20: java.lang.NullPointerException
>>>>>>> 069492ed1c47821f77e483ed6a9d34242fbb67bb
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
<<<<<<< HEAD
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:347)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:214)
=======
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:355)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:212)
>>>>>>> 069492ed1c47821f77e483ed6a9d34242fbb67bb
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
<<<<<<< HEAD
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:347)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:214)
=======
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:355)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:212)
>>>>>>> 069492ed1c47821f77e483ed6a9d34242fbb67bb
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
<<<<<<< HEAD
	at java.lang.Thread.run(Thread.java:748)

20190607-14:13:07: MsgSeqNum too high, expecting 2 but received 3: 8=FIX.4.49=22335=R34=343=Y49=EXC52=20190607-14:13:07.37556=001122=20190607-14:13:07.262131=20190607-000000000012.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=188
20190607-14:13:07: Enqueued at pos 3: 8=FIX.4.49=22335=R34=343=Y49=EXC52=20190607-14:13:07.37556=001122=20190607-14:13:07.262131=20190607-000000000012.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=188
20190607-14:13:07: Sent ResendRequest FROM: 2 TO: 2
20190607-14:13:07: Received SequenceReset FROM: 2 TO: 5
20190607-14:13:07: Received SequenceReset FROM: 5 TO: 6
20190607-15:35:41: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-15:35:41: Created session: FIX.4.4:001/001B27->EXC
20190607-15:35:42: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-15:35:42: MINA session created: local=/172.16.0.229:62508, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-15:35:43: Initiated logon request
20190607-15:35:43: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-15:35:43: Received logon
20190607-16:16:16: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-16:16:16: Created session: FIX.4.4:001/001B27->EXC
20190607-16:16:17: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-16:16:17: MINA session created: local=/172.16.0.229:63190, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-16:16:18: Initiated logon request
20190607-16:16:18: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-16:16:18: Received logon
20190607-16:39:53: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-16:39:53: Created session: FIX.4.4:001/001B27->EXC
20190607-16:39:53: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-16:39:53: MINA session created: local=/172.16.0.229:63625, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-16:39:55: Initiated logon request
20190607-16:39:55: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-16:39:55: Received logon
20190607-16:43:03: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-16:43:03: Created session: FIX.4.4:001/001B27->EXC
20190607-16:43:03: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-16:43:03: MINA session created: local=/172.16.0.229:63765, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-16:43:05: Initiated logon request
20190607-16:43:05: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-16:43:05: Received logon
20190607-16:44:14: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-16:44:14: Created session: FIX.4.4:001/001B27->EXC
20190607-16:44:15: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-16:44:15: MINA session created: local=/172.16.0.229:63884, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-16:44:16: Initiated logon request
20190607-16:44:16: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-16:44:16: Received logon
20190607-16:44:36: Rejecting invalid message: quickfix.FieldException: Required tag missing, field=38: 8=FIX.4.49=15135=AG34=549=EXC52=20190607-16:44:36.30056=00157=001B2758=(962): Deposito no fue ingresada131=4762034658=99146=155=TFIT16280428762=RFQF22=M10=054
20190607-16:44:36: Reject sent for Message 5: Required tag missing, field=38:38
20190607-16:47:03: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-16:47:03: Created session: FIX.4.4:001/001B27->EXC
20190607-16:47:03: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-16:47:03: MINA session created: local=/172.16.0.229:64017, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-16:47:05: Initiated logon request
20190607-16:47:05: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-16:47:05: Received logon
20190607-16:47:12: java.lang.NullPointerException
=======
	at java.lang.Thread.run(Unknown Source)

20190607-12:37:20: MsgSeqNum too high, expecting 2 but received 3: 8=FIX.4.49=22335=R34=343=Y49=EXC52=20190607-12:37:21.27156=001122=20190607-12:37:21.174131=20190607-000000000001.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=183
20190607-12:37:20: Enqueued at pos 3: 8=FIX.4.49=22335=R34=343=Y49=EXC52=20190607-12:37:21.27156=001122=20190607-12:37:21.174131=20190607-000000000001.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=183
20190607-12:37:20: Sent ResendRequest FROM: 2 TO: 2
20190607-12:37:20: Received SequenceReset FROM: 2 TO: 5
20190607-12:37:20: Received SequenceReset FROM: 5 TO: 6
20190607-13:06:51: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-13:06:51: Created session: FIX.4.4:001/001B27->EXC
20190607-13:06:51: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-13:06:51: MINA session created: local=/172.16.1.1:62111, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-13:06:52: Initiated logon request
20190607-13:06:52: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-13:06:52: Received logon
20190607-13:06:55: java.lang.NullPointerException
>>>>>>> 069492ed1c47821f77e483ed6a9d34242fbb67bb
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
<<<<<<< HEAD
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.ValidarRPrima(Validaciones.java:83)
	at co.bvc.com.orquestador.AutoEngine.validarR(AutoEngine.java:250)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:194)
=======
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:355)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:212)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:355)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:212)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190607-13:06:55: MsgSeqNum too high, expecting 2 but received 3: 8=FIX.4.49=19235=R34=349=EXC52=20190607-13:06:54.72556=001131=20190607-000000000002.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=191
20190607-13:06:55: Enqueued at pos 3: 8=FIX.4.49=19235=R34=349=EXC52=20190607-13:06:54.72556=001131=20190607-000000000002.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=191
20190607-13:06:55: Sent ResendRequest FROM: 2 TO: 2
20190607-13:06:55: ResendRequest for messages FROM 2 TO 2 has been satisfied.
20190607-13:06:55: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:355)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:212)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:355)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:212)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190607-13:06:55: MsgSeqNum too high, expecting 2 but received 3: 8=FIX.4.49=22335=R34=343=Y49=EXC52=20190607-13:06:54.79256=001122=20190607-13:06:54.725131=20190607-000000000002.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=200
20190607-13:06:55: Enqueued at pos 3: 8=FIX.4.49=22335=R34=343=Y49=EXC52=20190607-13:06:54.79256=001122=20190607-13:06:54.725131=20190607-000000000002.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=200
20190607-13:06:55: Sent ResendRequest FROM: 2 TO: 2
20190607-13:06:55: Received SequenceReset FROM: 2 TO: 5
20190607-13:06:55: Received SequenceReset FROM: 5 TO: 6
20190607-13:41:36: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-13:41:36: Created session: FIX.4.4:001/001B27->EXC
20190607-13:41:36: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-13:41:36: MINA session created: local=/172.16.1.1:62771, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-13:41:37: Initiated logon request
20190607-13:41:37: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-13:41:37: Received logon
20190607-13:44:48: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-13:44:48: Created session: FIX.4.4:001/001B27->EXC
20190607-13:44:48: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-13:44:48: MINA session created: local=/172.16.1.1:62866, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-13:44:49: Initiated logon request
20190607-13:44:49: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-13:44:49: Received logon
20190607-13:44:52: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:209)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:209)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190607-13:44:52: MsgSeqNum too high, expecting 2 but received 3: 8=FIX.4.49=19235=R34=349=EXC52=20190607-13:44:51.62456=001131=20190607-000000000004.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=190
20190607-13:44:52: Enqueued at pos 3: 8=FIX.4.49=19235=R34=349=EXC52=20190607-13:44:51.62456=001131=20190607-000000000004.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=190
20190607-13:44:52: Sent ResendRequest FROM: 2 TO: 2
20190607-13:44:52: ResendRequest for messages FROM 2 TO 2 has been satisfied.
20190607-13:44:52: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:209)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:209)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190607-13:44:52: MsgSeqNum too high, expecting 2 but received 3: 8=FIX.4.49=22335=R34=343=Y49=EXC52=20190607-13:44:51.76756=001122=20190607-13:44:51.624131=20190607-000000000004.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=200
20190607-13:44:52: Enqueued at pos 3: 8=FIX.4.49=22335=R34=343=Y49=EXC52=20190607-13:44:51.76756=001122=20190607-13:44:51.624131=20190607-000000000004.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=200
20190607-13:44:52: Sent ResendRequest FROM: 2 TO: 2
20190607-13:44:52: Received SequenceReset FROM: 2 TO: 5
20190607-13:44:52: Received SequenceReset FROM: 5 TO: 6
20190607-13:44:52: ResendRequest for messages FROM 2 TO 2 has been satisfied.
20190607-13:44:52: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:209)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:209)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190607-13:44:52: MsgSeqNum too high, expecting 6 but received 7: 8=FIX.4.49=19235=R34=749=EXC52=20190607-13:44:52.35356=001131=20190607-000000000005.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=195
20190607-13:44:52: Enqueued at pos 7: 8=FIX.4.49=19235=R34=749=EXC52=20190607-13:44:52.35356=001131=20190607-000000000005.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=195
20190607-13:44:52: Sent ResendRequest FROM: 6 TO: 6
20190607-13:44:52: ResendRequest for messages FROM 6 TO 6 has been satisfied.
20190607-13:44:52: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:209)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:209)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190607-13:44:52: MsgSeqNum too high, expecting 6 but received 7: 8=FIX.4.49=22335=R34=743=Y49=EXC52=20190607-13:44:52.39556=001122=20190607-13:44:52.353131=20190607-000000000005.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=203
20190607-13:44:52: Enqueued at pos 7: 8=FIX.4.49=22335=R34=743=Y49=EXC52=20190607-13:44:52.39556=001122=20190607-13:44:52.353131=20190607-000000000005.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=203
20190607-13:44:52: Sent ResendRequest FROM: 6 TO: 6
20190607-13:44:52: Received SequenceReset FROM: 6 TO: 9
20190607-13:44:52: Received SequenceReset FROM: 9 TO: 10
20190607-14:07:58: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-14:07:58: Created session: FIX.4.4:001/001B27->EXC
20190607-14:07:58: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-14:07:58: MINA session created: local=/172.16.1.1:63335, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-14:07:59: Initiated logon request
20190607-14:07:59: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-14:07:59: Received logon
20190607-14:08:02: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:209)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:209)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190607-14:08:02: MsgSeqNum too high, expecting 2 but received 3: 8=FIX.4.49=19235=R34=349=EXC52=20190607-14:08:01.71756=001131=20190607-000000000007.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=192
20190607-14:08:02: Enqueued at pos 3: 8=FIX.4.49=19235=R34=349=EXC52=20190607-14:08:01.71756=001131=20190607-000000000007.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=192
20190607-14:08:02: Sent ResendRequest FROM: 2 TO: 2
20190607-14:08:02: ResendRequest for messages FROM 2 TO 2 has been satisfied.
20190607-14:08:02: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:209)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:209)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190607-14:08:02: MsgSeqNum too high, expecting 2 but received 3: 8=FIX.4.49=22335=R34=343=Y49=EXC52=20190607-14:08:01.78956=001122=20190607-14:08:01.717131=20190607-000000000007.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=202
20190607-14:08:02: Enqueued at pos 3: 8=FIX.4.49=22335=R34=343=Y49=EXC52=20190607-14:08:01.78956=001122=20190607-14:08:01.717131=20190607-000000000007.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=202
20190607-14:08:02: Sent ResendRequest FROM: 2 TO: 2
20190607-14:08:02: Received SequenceReset FROM: 2 TO: 5
20190607-14:08:02: Received SequenceReset FROM: 5 TO: 6
20190607-14:08:02: ResendRequest for messages FROM 2 TO 2 has been satisfied.
20190607-14:08:02: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:209)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:209)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190607-14:08:02: MsgSeqNum too high, expecting 6 but received 7: 8=FIX.4.49=19235=R34=749=EXC52=20190607-14:08:02.58656=001131=20190607-000000000008.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=202
20190607-14:08:02: Enqueued at pos 7: 8=FIX.4.49=19235=R34=749=EXC52=20190607-14:08:02.58656=001131=20190607-000000000008.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=202
20190607-14:08:02: Sent ResendRequest FROM: 6 TO: 6
20190607-14:08:02: ResendRequest for messages FROM 6 TO 6 has been satisfied.
20190607-14:08:03: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:209)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:209)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190607-14:08:03: MsgSeqNum too high, expecting 6 but received 7: 8=FIX.4.49=22335=R34=743=Y49=EXC52=20190607-14:08:02.63556=001122=20190607-14:08:02.586131=20190607-000000000008.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=203
20190607-14:08:03: Enqueued at pos 7: 8=FIX.4.49=22335=R34=743=Y49=EXC52=20190607-14:08:02.63556=001122=20190607-14:08:02.586131=20190607-000000000008.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=203
20190607-14:08:03: Sent ResendRequest FROM: 6 TO: 6
20190607-14:08:03: Received SequenceReset FROM: 6 TO: 9
20190607-14:08:03: Received SequenceReset FROM: 9 TO: 10
20190607-14:08:32: ResendRequest for messages FROM 6 TO 6 has been satisfied.
20190607-14:10:39: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-14:10:39: Created session: FIX.4.4:001/001B27->EXC
20190607-14:10:40: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-14:10:40: MINA session created: local=/172.16.1.1:63438, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-14:10:41: Initiated logon request
20190607-14:10:41: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-14:10:41: Received logon
20190607-14:10:43: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:209)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:209)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190607-14:10:43: MsgSeqNum too high, expecting 2 but received 3: 8=FIX.4.49=19235=R34=349=EXC52=20190607-14:10:43.32056=001131=20190607-000000000009.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=183
20190607-14:10:43: Enqueued at pos 3: 8=FIX.4.49=19235=R34=349=EXC52=20190607-14:10:43.32056=001131=20190607-000000000009.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=183
20190607-14:10:43: Sent ResendRequest FROM: 2 TO: 2
20190607-14:10:43: ResendRequest for messages FROM 2 TO 2 has been satisfied.
20190607-14:10:43: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:209)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:209)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190607-14:10:43: MsgSeqNum too high, expecting 2 but received 3: 8=FIX.4.49=22335=R34=343=Y49=EXC52=20190607-14:10:43.38356=001122=20190607-14:10:43.320131=20190607-000000000009.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=182
20190607-14:10:43: Enqueued at pos 3: 8=FIX.4.49=22335=R34=343=Y49=EXC52=20190607-14:10:43.38356=001122=20190607-14:10:43.320131=20190607-000000000009.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=182
20190607-14:10:43: Sent ResendRequest FROM: 2 TO: 2
20190607-14:10:43: Received SequenceReset FROM: 2 TO: 5
20190607-14:10:43: Received SequenceReset FROM: 5 TO: 6
20190607-14:10:44: ResendRequest for messages FROM 2 TO 2 has been satisfied.
20190607-14:10:44: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:209)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:209)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190607-14:10:44: MsgSeqNum too high, expecting 6 but received 7: 8=FIX.4.49=19235=R34=749=EXC52=20190607-14:10:44.02256=001131=20190607-000000000010.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=179
20190607-14:10:44: Enqueued at pos 7: 8=FIX.4.49=19235=R34=749=EXC52=20190607-14:10:44.02256=001131=20190607-000000000010.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=179
20190607-14:10:44: Sent ResendRequest FROM: 6 TO: 6
20190607-14:10:44: ResendRequest for messages FROM 6 TO 6 has been satisfied.
20190607-14:10:44: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:209)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:209)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190607-14:10:44: MsgSeqNum too high, expecting 6 but received 7: 8=FIX.4.49=22335=R34=743=Y49=EXC52=20190607-14:10:44.06056=001122=20190607-14:10:44.022131=20190607-000000000010.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=171
20190607-14:10:44: Enqueued at pos 7: 8=FIX.4.49=22335=R34=743=Y49=EXC52=20190607-14:10:44.06056=001122=20190607-14:10:44.022131=20190607-000000000010.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=171
20190607-14:10:44: Sent ResendRequest FROM: 6 TO: 6
20190607-14:10:44: Received SequenceReset FROM: 6 TO: 9
20190607-14:10:44: Received SequenceReset FROM: 9 TO: 10
20190607-14:11:14: ResendRequest for messages FROM 6 TO 6 has been satisfied.
20190607-14:22:12: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-14:22:12: Created session: FIX.4.4:001/001B27->EXC
20190607-14:22:12: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-14:22:12: MINA session created: local=/172.16.1.1:63793, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-14:22:14: Initiated logon request
20190607-14:22:14: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-14:22:14: Received logon
20190607-14:23:01: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-14:23:01: Created session: FIX.4.4:001/001B27->EXC
20190607-14:23:01: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-14:23:01: MINA session created: local=/172.16.1.1:63864, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-14:23:02: Initiated logon request
20190607-14:23:02: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-14:23:02: Received logon
20190607-14:23:30: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-14:23:30: Created session: FIX.4.4:001/001B27->EXC
20190607-14:23:30: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-14:23:30: MINA session created: local=/172.16.1.1:63947, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-14:23:31: Initiated logon request
20190607-14:23:31: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-14:23:31: Received logon
20190607-14:23:33: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:210)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:210)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190607-14:23:33: MsgSeqNum too high, expecting 2 but received 3: 8=FIX.4.49=19235=R34=349=EXC52=20190607-14:23:34.06356=001131=20190607-000000000016.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=189
20190607-14:23:33: Enqueued at pos 3: 8=FIX.4.49=19235=R34=349=EXC52=20190607-14:23:34.06356=001131=20190607-000000000016.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=189
20190607-14:23:33: Sent ResendRequest FROM: 2 TO: 2
20190607-14:23:33: ResendRequest for messages FROM 2 TO 2 has been satisfied.
20190607-14:23:33: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:210)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:210)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190607-14:23:33: MsgSeqNum too high, expecting 2 but received 3: 8=FIX.4.49=22335=R34=343=Y49=EXC52=20190607-14:23:34.12756=001122=20190607-14:23:34.063131=20190607-000000000016.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=188
20190607-14:23:33: Enqueued at pos 3: 8=FIX.4.49=22335=R34=343=Y49=EXC52=20190607-14:23:34.12756=001122=20190607-14:23:34.063131=20190607-000000000016.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=188
20190607-14:23:33: Sent ResendRequest FROM: 2 TO: 2
20190607-14:23:33: Received SequenceReset FROM: 2 TO: 5
20190607-14:23:33: Received SequenceReset FROM: 5 TO: 6
20190607-14:24:03: ResendRequest for messages FROM 2 TO 2 has been satisfied.
20190607-14:42:13: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-14:42:13: Created session: FIX.4.4:001/001B27->EXC
20190607-14:42:13: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-14:42:13: MINA session created: local=/172.16.1.1:64255, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-14:42:14: Initiated logon request
20190607-14:42:14: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-14:42:14: Received logon
20190607-14:42:17: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:210)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:210)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190607-14:42:17: MsgSeqNum too high, expecting 2 but received 3: 8=FIX.4.49=19235=R34=349=EXC52=20190607-14:42:17.28856=001131=20190607-000000000017.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=201
20190607-14:42:17: Enqueued at pos 3: 8=FIX.4.49=19235=R34=349=EXC52=20190607-14:42:17.28856=001131=20190607-000000000017.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=201
20190607-14:42:17: Sent ResendRequest FROM: 2 TO: 2
20190607-14:42:17: ResendRequest for messages FROM 2 TO 2 has been satisfied.
20190607-14:42:17: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:210)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:210)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190607-14:42:17: MsgSeqNum too high, expecting 2 but received 3: 8=FIX.4.49=22335=R34=343=Y49=EXC52=20190607-14:42:17.39656=001122=20190607-14:42:17.288131=20190607-000000000017.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=210
20190607-14:42:17: Enqueued at pos 3: 8=FIX.4.49=22335=R34=343=Y49=EXC52=20190607-14:42:17.39656=001122=20190607-14:42:17.288131=20190607-000000000017.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=210
20190607-14:42:17: Sent ResendRequest FROM: 2 TO: 2
20190607-14:42:17: Received SequenceReset FROM: 2 TO: 5
20190607-14:42:17: Received SequenceReset FROM: 5 TO: 6
20190607-14:45:46: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-14:45:46: Created session: FIX.4.4:001/001B27->EXC
20190607-14:45:46: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-14:45:46: MINA session created: local=/172.16.1.1:64362, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-14:45:47: Initiated logon request
20190607-14:45:47: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-14:45:47: Received logon
20190607-14:45:49: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:210)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:210)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190607-14:45:49: MsgSeqNum too high, expecting 2 but received 3: 8=FIX.4.49=19235=R34=349=EXC52=20190607-14:45:49.66356=001131=20190607-000000000018.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=207
20190607-14:45:49: Enqueued at pos 3: 8=FIX.4.49=19235=R34=349=EXC52=20190607-14:45:49.66356=001131=20190607-000000000018.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=207
20190607-14:45:49: Sent ResendRequest FROM: 2 TO: 2
20190607-14:45:49: ResendRequest for messages FROM 2 TO 2 has been satisfied.
20190607-14:45:49: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:210)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:210)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190607-14:45:49: MsgSeqNum too high, expecting 2 but received 3: 8=FIX.4.49=22335=R34=343=Y49=EXC52=20190607-14:45:49.72156=001122=20190607-14:45:49.663131=20190607-000000000018.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=216
20190607-14:45:49: Enqueued at pos 3: 8=FIX.4.49=22335=R34=343=Y49=EXC52=20190607-14:45:49.72156=001122=20190607-14:45:49.663131=20190607-000000000018.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=216
20190607-14:45:49: Sent ResendRequest FROM: 2 TO: 2
20190607-14:45:49: Received SequenceReset FROM: 2 TO: 5
20190607-14:45:49: Received SequenceReset FROM: 5 TO: 6
20190607-14:46:18: ResendRequest for messages FROM 2 TO 2 has been satisfied.
20190607-14:51:24: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-14:51:24: Created session: FIX.4.4:001/001B27->EXC
20190607-14:51:24: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-14:51:24: MINA session created: local=/172.16.1.1:64564, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-14:51:25: Initiated logon request
20190607-14:51:26: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-14:51:26: Received logon
20190607-14:54:08: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-14:54:08: Created session: FIX.4.4:001/001B27->EXC
20190607-14:54:08: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-14:54:08: MINA session created: local=/172.16.1.1:64674, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-14:54:09: Initiated logon request
20190607-14:54:09: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-14:54:09: Received logon
20190607-14:54:12: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:210)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:210)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190607-14:54:12: MsgSeqNum too high, expecting 2 but received 3: 8=FIX.4.49=19235=R34=349=EXC52=20190607-14:54:12.26256=001131=20190607-000000000020.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=185
20190607-14:54:12: Enqueued at pos 3: 8=FIX.4.49=19235=R34=349=EXC52=20190607-14:54:12.26256=001131=20190607-000000000020.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=185
20190607-14:54:12: Sent ResendRequest FROM: 2 TO: 2
20190607-14:54:12: ResendRequest for messages FROM 2 TO 2 has been satisfied.
20190607-14:54:12: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:210)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:210)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190607-14:54:12: MsgSeqNum too high, expecting 2 but received 3: 8=FIX.4.49=22335=R34=343=Y49=EXC52=20190607-14:54:12.32256=001122=20190607-14:54:12.262131=20190607-000000000020.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=181
20190607-14:54:12: Enqueued at pos 3: 8=FIX.4.49=22335=R34=343=Y49=EXC52=20190607-14:54:12.32256=001122=20190607-14:54:12.262131=20190607-000000000020.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=181
20190607-14:54:12: Sent ResendRequest FROM: 2 TO: 2
20190607-14:54:12: Received SequenceReset FROM: 2 TO: 5
20190607-14:54:12: Received SequenceReset FROM: 5 TO: 6
20190607-14:55:36: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-14:55:36: Created session: FIX.4.4:001/001B27->EXC
20190607-14:55:36: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-14:55:36: MINA session created: local=/172.16.1.1:64750, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-14:55:37: Initiated logon request
20190607-14:55:37: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-14:55:37: Received logon
20190607-14:57:51: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-14:57:51: Created session: FIX.4.4:001/001B27->EXC
20190607-14:57:51: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-14:57:51: MINA session created: local=/172.16.1.1:64840, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-14:57:52: Initiated logon request
20190607-14:57:52: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-14:57:52: Received logon
20190607-14:57:54: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:210)
>>>>>>> 069492ed1c47821f77e483ed6a9d34242fbb67bb
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
<<<<<<< HEAD
	at co.bvc.com.test.Validaciones.ValidarRPrima(Validaciones.java:83)
	at co.bvc.com.orquestador.AutoEngine.validarR(AutoEngine.java:250)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:194)
=======
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:210)
>>>>>>> 069492ed1c47821f77e483ed6a9d34242fbb67bb
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
<<<<<<< HEAD
	at java.lang.Thread.run(Thread.java:748)

20190607-16:53:10: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-16:53:10: Created session: FIX.4.4:001/001B27->EXC
20190607-16:53:11: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-16:53:11: MINA session created: local=/172.16.0.229:64195, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-16:53:12: Initiated logon request
20190607-16:53:12: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-16:53:12: Received logon
20190607-16:53:33: Rejecting invalid message: quickfix.FieldException: Required tag missing, field=38: 8=FIX.4.49=15235=AG34=549=EXC52=20190607-16:53:33.38456=00157=001B2758=(962): Deposito no fue ingresada131=79665886658=99146=155=TFIT16280428762=RFQF22=M10=141
20190607-16:53:33: Reject sent for Message 5: Required tag missing, field=38:38
20190607-17:01:24: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-17:01:24: Created session: FIX.4.4:001/001B27->EXC
20190607-17:01:24: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-17:01:24: MINA session created: local=/172.16.0.229:64530, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-17:01:26: Initiated logon request
20190607-17:01:26: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-17:01:26: Received logon
20190607-17:01:33: java.lang.NullPointerException
=======
	at java.lang.Thread.run(Unknown Source)

20190607-14:57:54: MsgSeqNum too high, expecting 2 but received 3: 8=FIX.4.49=19235=R34=349=EXC52=20190607-14:57:54.87356=001131=20190607-000000000022.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=204
20190607-14:57:54: Enqueued at pos 3: 8=FIX.4.49=19235=R34=349=EXC52=20190607-14:57:54.87356=001131=20190607-000000000022.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=204
20190607-14:57:54: Sent ResendRequest FROM: 2 TO: 2
20190607-14:57:54: ResendRequest for messages FROM 2 TO 2 has been satisfied.
20190607-14:57:54: java.lang.NullPointerException
>>>>>>> 069492ed1c47821f77e483ed6a9d34242fbb67bb
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
<<<<<<< HEAD
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.ValidarRPrima(Validaciones.java:83)
	at co.bvc.com.orquestador.AutoEngine.validarR(AutoEngine.java:250)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:194)
=======
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:210)
>>>>>>> 069492ed1c47821f77e483ed6a9d34242fbb67bb
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
<<<<<<< HEAD
	at co.bvc.com.test.Validaciones.ValidarRPrima(Validaciones.java:83)
	at co.bvc.com.orquestador.AutoEngine.validarR(AutoEngine.java:250)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:194)
=======
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:443)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:350)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:210)
>>>>>>> 069492ed1c47821f77e483ed6a9d34242fbb67bb
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
<<<<<<< HEAD
	at java.lang.Thread.run(Thread.java:748)

20190607-17:05:57: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-17:05:57: Created session: FIX.4.4:001/001B27->EXC
20190607-17:05:57: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-17:05:58: MINA session created: local=/172.16.0.229:64703, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-17:05:59: Initiated logon request
20190607-17:05:59: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-17:05:59: Received logon
20190607-17:06:19: Rejecting invalid message: quickfix.FieldException: Required tag missing, field=38: 8=FIX.4.49=15235=AG34=549=EXC52=20190607-17:06:19.72856=00157=001B2758=(962): Deposito no fue ingresada131=75330286658=99146=155=TFIT16280428762=RFQF22=M10=125
20190607-17:06:19: Reject sent for Message 5: Required tag missing, field=38:38
=======
	at java.lang.Thread.run(Unknown Source)

20190607-14:57:54: MsgSeqNum too high, expecting 2 but received 3: 8=FIX.4.49=22335=R34=343=Y49=EXC52=20190607-14:57:54.94456=001122=20190607-14:57:54.873131=20190607-000000000022.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=219
20190607-14:57:54: Enqueued at pos 3: 8=FIX.4.49=22335=R34=343=Y49=EXC52=20190607-14:57:54.94456=001122=20190607-14:57:54.873131=20190607-000000000022.00146=155=TFIT15260826762=RFQF48=2034822=M54=138=1500000000453=2448=001B27447=C452=12448=001447=C452=110=219
20190607-14:57:54: Sent ResendRequest FROM: 2 TO: 2
20190607-14:57:54: Received SequenceReset FROM: 2 TO: 5
20190607-14:57:54: Received SequenceReset FROM: 5 TO: 6
20190607-14:58:23: ResendRequest for messages FROM 2 TO 2 has been satisfied.
<<<<<<< HEAD
20190607-15:15:31: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-15:15:31: Created session: FIX.4.4:001/001B27->EXC
20190607-15:15:31: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-15:15:31: MINA session created: local=/172.16.1.1:65191, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-15:15:32: Initiated logon request
20190607-15:15:32: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-15:15:32: Received logon
20190607-15:15:40: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.ValidarRPrima(Validaciones.java:83)
	at co.bvc.com.orquestador.AutoEngine.validarR(AutoEngine.java:252)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:186)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.ValidarRPrima(Validaciones.java:83)
	at co.bvc.com.orquestador.AutoEngine.validarR(AutoEngine.java:252)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:186)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190607-15:18:15: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-15:18:15: Created session: FIX.4.4:001/001B27->EXC
20190607-15:18:16: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-15:18:16: MINA session created: local=/172.16.1.1:65292, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-15:18:17: Initiated logon request
20190607-15:18:17: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-15:18:17: Received logon
20190607-15:18:24: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.ValidarRPrima(Validaciones.java:83)
	at co.bvc.com.orquestador.AutoEngine.validarR(AutoEngine.java:252)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:186)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.ValidarRPrima(Validaciones.java:83)
	at co.bvc.com.orquestador.AutoEngine.validarR(AutoEngine.java:252)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:186)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190607-15:18:48: MsgSeqNum too high, expecting 2 but received 3: 8=FIX.4.49=4935=034=349=EXC52=20190607-15:18:49.00056=00110=081
20190607-15:18:48: Enqueued at pos 3: 8=FIX.4.49=4935=034=349=EXC52=20190607-15:18:49.00056=00110=081
20190607-15:18:48: Sent ResendRequest FROM: 2 TO: 2
20190607-15:18:49: ResendRequest for messages FROM 2 TO 2 has been satisfied.
20190607-15:18:54: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.ValidarRPrima(Validaciones.java:83)
	at co.bvc.com.orquestador.AutoEngine.validarR(AutoEngine.java:252)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:186)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.ValidarRPrima(Validaciones.java:83)
	at co.bvc.com.orquestador.AutoEngine.validarR(AutoEngine.java:252)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:186)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190607-15:18:54: MsgSeqNum too high, expecting 2 but received 3: 8=FIX.4.49=6535=434=343=Y49=EXC52=20190607-15:18:49.02456=00136=4123=Y10=095
20190607-15:18:54: Enqueued at pos 3: 8=FIX.4.49=6535=434=343=Y49=EXC52=20190607-15:18:49.02456=00136=4123=Y10=095
20190607-15:18:54: Sent ResendRequest FROM: 2 TO: 2
20190607-15:18:54: Received SequenceReset FROM: 2 TO: 5
20190607-15:18:54: Received SequenceReset FROM: 5 TO: 6
20190607-15:21:42: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-15:21:42: Created session: FIX.4.4:001/001B27->EXC
20190607-15:21:42: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-15:21:42: MINA session created: local=/172.16.1.1:65399, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-15:21:43: Initiated logon request
20190607-15:21:43: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-15:21:43: Received logon
20190607-15:21:51: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.ValidarRPrima(Validaciones.java:83)
	at co.bvc.com.orquestador.AutoEngine.validarR(AutoEngine.java:252)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:186)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.ValidarRPrima(Validaciones.java:83)
	at co.bvc.com.orquestador.AutoEngine.validarR(AutoEngine.java:252)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:186)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190607-15:22:15: MsgSeqNum too high, expecting 2 but received 3: 8=FIX.4.49=4935=034=349=EXC52=20190607-15:22:16.00056=00110=070
20190607-15:22:15: Enqueued at pos 3: 8=FIX.4.49=4935=034=349=EXC52=20190607-15:22:16.00056=00110=070
20190607-15:22:15: Sent ResendRequest FROM: 2 TO: 2
20190607-15:22:16: ResendRequest for messages FROM 2 TO 2 has been satisfied.
20190607-15:22:21: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.ValidarRPrima(Validaciones.java:83)
	at co.bvc.com.orquestador.AutoEngine.validarR(AutoEngine.java:252)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:186)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.ValidarRPrima(Validaciones.java:83)
	at co.bvc.com.orquestador.AutoEngine.validarR(AutoEngine.java:252)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:186)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190607-15:22:21: MsgSeqNum too high, expecting 2 but received 3: 8=FIX.4.49=6535=434=343=Y49=EXC52=20190607-15:22:16.02156=00136=4123=Y10=081
20190607-15:22:21: Enqueued at pos 3: 8=FIX.4.49=6535=434=343=Y49=EXC52=20190607-15:22:16.02156=00136=4123=Y10=081
20190607-15:22:21: Sent ResendRequest FROM: 2 TO: 2
20190607-15:22:21: Received SequenceReset FROM: 2 TO: 5
20190607-15:22:21: Received SequenceReset FROM: 5 TO: 6
20190607-15:22:50: ResendRequest for messages FROM 2 TO 2 has been satisfied.
20190607-16:29:57: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-16:29:57: Created session: FIX.4.4:001/001B27->EXC
20190607-16:29:57: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-16:29:57: MINA session created: local=/172.16.1.1:49919, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-16:29:58: Initiated logon request
20190607-16:29:58: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-16:29:58: Received logon
20190607-16:30:46: Sent test request TEST
20190607-16:31:13: Disconnecting: Timed out waiting for heartbeat
20190607-16:31:14: MINA session created: local=/172.16.1.1:49998, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-16:31:14: Initiated logon request
20190607-16:31:25: Disconnecting: Timed out waiting for logon response
20190607-16:31:47: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-16:31:47: Created session: FIX.4.4:001/001B27->EXC
20190607-16:31:48: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-16:31:48: MINA session created: local=/172.16.1.1:50130, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-16:31:49: Initiated logon request
20190607-16:31:49: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-16:31:49: Received logon
20190607-16:32:33: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.ValidarRPrima(Validaciones.java:83)
	at co.bvc.com.orquestador.AutoEngine.validarR(AutoEngine.java:252)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:186)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.ValidarRPrima(Validaciones.java:83)
	at co.bvc.com.orquestador.AutoEngine.validarR(AutoEngine.java:252)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:186)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190607-16:32:37: Sent test request TEST
20190607-16:32:38: MsgSeqNum too high, expecting 2 but received 3: 8=FIX.4.49=4935=034=349=EXC52=20190607-16:32:21.00056=00110=068
20190607-16:32:38: Enqueued at pos 3: 8=FIX.4.49=4935=034=349=EXC52=20190607-16:32:21.00056=00110=068
20190607-16:32:38: Sent ResendRequest FROM: 2 TO: 2
20190607-16:32:41: MsgSeqNum too high, expecting 2 but received 4: 8=FIX.4.49=5835=034=449=EXC52=20190607-16:32:37.04756=001112=TEST10=105
20190607-16:32:41: Enqueued at pos 4: 8=FIX.4.49=5835=034=449=EXC52=20190607-16:32:37.04756=001112=TEST10=105
20190607-16:32:41: Already sent ResendRequest FROM: 2 TO: 2.  Not sending another.
20190607-16:32:43: ResendRequest for messages FROM 2 TO 2 has been satisfied.
20190607-16:51:44: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-16:51:44: Created session: FIX.4.4:001/001B27->EXC
20190607-16:51:44: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-16:51:44: MINA session created: local=/172.16.1.1:50456, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-16:51:45: Initiated logon request
20190607-16:51:45: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-16:51:45: Received logon
20190607-16:51:53: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.ValidarRPrima(Validaciones.java:83)
	at co.bvc.com.orquestador.AutoEngine.validarR(AutoEngine.java:252)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:186)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.ValidarRPrima(Validaciones.java:83)
	at co.bvc.com.orquestador.AutoEngine.validarR(AutoEngine.java:252)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:186)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190607-17:00:18: Session FIX.4.4:001/001B27->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190607-17:00:18: Created session: FIX.4.4:001/001B27->EXC
20190607-17:00:18: Configured socket addresses for session: [/172.36.2.13:54401]
20190607-17:00:18: MINA session created: local=/172.16.1.1:50651, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54401
20190607-17:00:19: Initiated logon request
20190607-17:00:19: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190607-17:00:19: Received logon
20190607-17:00:32: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.ValidarRPrima(Validaciones.java:83)
	at co.bvc.com.orquestador.AutoEngine.validarR(AutoEngine.java:252)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:186)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.ValidarRPrima(Validaciones.java:83)
	at co.bvc.com.orquestador.AutoEngine.validarR(AutoEngine.java:252)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:186)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190607-17:00:52: MsgSeqNum too high, expecting 2 but received 3: 8=FIX.4.49=4935=034=349=EXC52=20190607-17:00:52.00056=00110=068
20190607-17:00:52: Enqueued at pos 3: 8=FIX.4.49=4935=034=349=EXC52=20190607-17:00:52.00056=00110=068
20190607-17:00:52: Sent ResendRequest FROM: 2 TO: 2
20190607-17:00:52: ResendRequest for messages FROM 2 TO 2 has been satisfied.
=======
>>>>>>> 069492ed1c47821f77e483ed6a9d34242fbb67bb
>>>>>>> da02556c5d143e2f747792af737c29298e2fe0f4
