20190612-16:29:18: Session FIX.4.4:002/002B35->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190612-16:29:18: Created session: FIX.4.4:002/002B35->EXC
20190612-16:29:18: Configured socket addresses for session: [/172.36.2.13:54402]
20190612-16:29:18: MINA session created: local=/172.16.1.1:59586, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54402
20190612-16:29:19: Initiated logon request
20190612-16:29:19: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190612-16:29:19: Received logon
20190612-16:29:48: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:435)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:369)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:214)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:435)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:369)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:214)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190612-16:29:48: MsgSeqNum too high, expecting 3 but received 4: 8=FIX.4.49=51535=834=449=EXC52=20190612-16:29:48.73256=00257=002B356=79.41411=20190612112917_S14=50000000017=1522=M31=79.41432=50000000037=038=50000000039=248=2062654=255=TFIC1328042560=20190612-16:29:48.73263=164=2019061275=20190612150=F151=0381=397072500.000762=RFQF828=99880=2019061200000000661080=20190612-000000000048.001081=61623=4.00020102=79.414453=6448=002B35447=C452=12448=002447=C452=1448=001B27447=C452=37448=001447=C452=17448=002FCM001447=C452=36448=DCV447=C452=1010=061
20190612-16:29:48: Enqueued at pos 4: 8=FIX.4.49=51535=834=449=EXC52=20190612-16:29:48.73256=00257=002B356=79.41411=20190612112917_S14=50000000017=1522=M31=79.41432=50000000037=038=50000000039=248=2062654=255=TFIC1328042560=20190612-16:29:48.73263=164=2019061275=20190612150=F151=0381=397072500.000762=RFQF828=99880=2019061200000000661080=20190612-000000000048.001081=61623=4.00020102=79.414453=6448=002B35447=C452=12448=002447=C452=1448=001B27447=C452=37448=001447=C452=17448=002FCM001447=C452=36448=DCV447=C452=1010=061
20190612-16:29:48: Sent ResendRequest FROM: 3 TO: 3
20190612-16:29:48: ResendRequest for messages FROM 3 TO 3 has been satisfied.
20190612-16:29:54: Processing queued message: 4
20190612-16:29:59: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.nextQueued(Session.java:2359)
	at quickfix.Session.nextQueued(Session.java:2349)
	at quickfix.Session.nextQueued(Session.java:2333)
	at quickfix.Session.next(Session.java:1136)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validarOcho(Validaciones.java:564)
	at co.bvc.com.orquestador.AutoEngine.validarAJ(AutoEngine.java:344)
	at co.bvc.com.test.AdapterIO.onMessage(AdapterIO.java:240)
	at quickfix.fix44.MessageCracker.crack44(MessageCracker.java:1329)
	at quickfix.fix44.MessageCracker.crack(MessageCracker.java:1231)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:232)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 10 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validarOcho(Validaciones.java:564)
	at co.bvc.com.orquestador.AutoEngine.validarAJ(AutoEngine.java:344)
	at co.bvc.com.test.AdapterIO.onMessage(AdapterIO.java:240)
	at quickfix.fix44.MessageCracker.crack44(MessageCracker.java:1329)
	at quickfix.fix44.MessageCracker.crack(MessageCracker.java:1231)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:232)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.nextQueued(Session.java:2359)
	at quickfix.Session.nextQueued(Session.java:2349)
	at quickfix.Session.nextQueued(Session.java:2333)
	at quickfix.Session.next(Session.java:1136)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190612-16:30:04: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validarOcho(Validaciones.java:564)
	at co.bvc.com.orquestador.AutoEngine.validarAJ(AutoEngine.java:344)
	at co.bvc.com.test.AdapterIO.onMessage(AdapterIO.java:240)
	at quickfix.fix44.MessageCracker.crack44(MessageCracker.java:1329)
	at quickfix.fix44.MessageCracker.crack(MessageCracker.java:1231)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:232)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validarOcho(Validaciones.java:564)
	at co.bvc.com.orquestador.AutoEngine.validarAJ(AutoEngine.java:344)
	at co.bvc.com.test.AdapterIO.onMessage(AdapterIO.java:240)
	at quickfix.fix44.MessageCracker.crack44(MessageCracker.java:1329)
	at quickfix.fix44.MessageCracker.crack(MessageCracker.java:1231)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:232)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190612-16:30:04: Received SequenceReset FROM: 4 TO: 6
20190612-16:44:38: Session FIX.4.4:002/002B35->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190612-16:44:38: Created session: FIX.4.4:002/002B35->EXC
20190612-16:44:38: Configured socket addresses for session: [/172.36.2.13:54402]
20190612-16:44:38: MINA session created: local=/172.16.1.1:59846, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54402
20190612-16:44:39: Initiated logon request
20190612-16:44:39: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190612-16:44:39: Received logon
20190612-16:45:13: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:435)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:369)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:215)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validaAI(Validaciones.java:435)
	at co.bvc.com.orquestador.AutoEngine.validarAI(AutoEngine.java:369)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:215)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190612-16:45:13: MsgSeqNum too high, expecting 3 but received 4: 8=FIX.4.49=51535=834=449=EXC52=20190612-16:45:13.64556=00257=002B356=79.41411=20190612114437_S14=50000000017=1622=M31=79.41432=50000000037=038=50000000039=248=2062654=255=TFIC1328042560=20190612-16:45:13.64563=164=2019061275=20190612150=F151=0381=397072500.000762=RFQF828=99880=2019061200000000701080=20190612-000000000055.001081=61623=4.00020102=79.414453=6448=002B35447=C452=12448=002447=C452=1448=001B27447=C452=37448=001447=C452=17448=002FCM001447=C452=36448=DCV447=C452=1010=040
20190612-16:45:13: Enqueued at pos 4: 8=FIX.4.49=51535=834=449=EXC52=20190612-16:45:13.64556=00257=002B356=79.41411=20190612114437_S14=50000000017=1622=M31=79.41432=50000000037=038=50000000039=248=2062654=255=TFIC1328042560=20190612-16:45:13.64563=164=2019061275=20190612150=F151=0381=397072500.000762=RFQF828=99880=2019061200000000701080=20190612-000000000055.001081=61623=4.00020102=79.414453=6448=002B35447=C452=12448=002447=C452=1448=001B27447=C452=37448=001447=C452=17448=002FCM001447=C452=36448=DCV447=C452=1010=040
20190612-16:45:13: Sent ResendRequest FROM: 3 TO: 3
20190612-16:45:13: ResendRequest for messages FROM 3 TO 3 has been satisfied.
20190612-16:45:19: Processing queued message: 4
20190612-16:45:24: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.nextQueued(Session.java:2359)
	at quickfix.Session.nextQueued(Session.java:2349)
	at quickfix.Session.nextQueued(Session.java:2333)
	at quickfix.Session.next(Session.java:1136)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validarOcho(Validaciones.java:564)
	at co.bvc.com.orquestador.AutoEngine.validarAJ(AutoEngine.java:344)
	at co.bvc.com.test.AdapterIO.onMessage(AdapterIO.java:241)
	at quickfix.fix44.MessageCracker.crack44(MessageCracker.java:1329)
	at quickfix.fix44.MessageCracker.crack(MessageCracker.java:1231)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:233)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 10 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validarOcho(Validaciones.java:564)
	at co.bvc.com.orquestador.AutoEngine.validarAJ(AutoEngine.java:344)
	at co.bvc.com.test.AdapterIO.onMessage(AdapterIO.java:241)
	at quickfix.fix44.MessageCracker.crack44(MessageCracker.java:1329)
	at quickfix.fix44.MessageCracker.crack(MessageCracker.java:1231)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:233)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.nextQueued(Session.java:2359)
	at quickfix.Session.nextQueued(Session.java:2349)
	at quickfix.Session.nextQueued(Session.java:2333)
	at quickfix.Session.next(Session.java:1136)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190612-16:45:29: java.lang.NullPointerException
quickfix.RuntimeError: java.lang.NullPointerException
	at quickfix.Session.next(Session.java:1130)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validarOcho(Validaciones.java:564)
	at co.bvc.com.orquestador.AutoEngine.validarAJ(AutoEngine.java:344)
	at co.bvc.com.test.AdapterIO.onMessage(AdapterIO.java:241)
	at quickfix.fix44.MessageCracker.crack44(MessageCracker.java:1329)
	at quickfix.fix44.MessageCracker.crack(MessageCracker.java:1231)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:233)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	... 6 more
Cause: null
java.lang.NullPointerException
	at co.bvc.com.test.Validaciones.validarOcho(Validaciones.java:564)
	at co.bvc.com.orquestador.AutoEngine.validarAJ(AutoEngine.java:344)
	at co.bvc.com.test.AdapterIO.onMessage(AdapterIO.java:241)
	at quickfix.fix44.MessageCracker.crack44(MessageCracker.java:1329)
	at quickfix.fix44.MessageCracker.crack(MessageCracker.java:1231)
	at co.bvc.com.test.AdapterIO.fromApp(AdapterIO.java:233)
	at quickfix.Session.fromCallback(Session.java:1818)
	at quickfix.Session.verify(Session.java:1762)
	at quickfix.Session.verify(Session.java:1833)
	at quickfix.Session.next(Session.java:1030)
	at quickfix.Session.next(Session.java:1173)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$SessionMessageEvent.processMessage(SingleThreadedEventHandlingStrategy.java:151)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.block(SingleThreadedEventHandlingStrategy.java:101)
	at quickfix.mina.SingleThreadedEventHandlingStrategy.lambda$blockInThread$0(SingleThreadedEventHandlingStrategy.java:133)
	at quickfix.mina.SingleThreadedEventHandlingStrategy$ThreadAdapter$RunnableWrapper.run(SingleThreadedEventHandlingStrategy.java:244)
	at java.lang.Thread.run(Unknown Source)

20190612-16:45:29: Received SequenceReset FROM: 4 TO: 6
20190612-16:55:02: Session FIX.4.4:002/002B35->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190612-16:55:02: Created session: FIX.4.4:002/002B35->EXC
20190612-16:55:02: Configured socket addresses for session: [/172.36.2.13:54402]
20190612-16:55:02: MINA session created: local=/172.16.1.1:60033, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54402
20190612-16:55:03: Initiated logon request
20190612-16:55:03: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190612-16:55:03: Received logon
20190612-16:56:22: Session FIX.4.4:002/002B35->EXC schedule is daily, 00:00:00-UTC - 23:59:59-UTC
20190612-16:56:22: Created session: FIX.4.4:002/002B35->EXC
20190612-16:56:22: Configured socket addresses for session: [/172.36.2.13:54402]
20190612-16:56:23: MINA session created: local=/172.16.1.1:60123, class org.apache.mina.transport.socket.nio.NioSocketSession, remote=/172.36.2.13:54402
20190612-16:56:24: Initiated logon request
20190612-16:56:24: Logon contains ResetSeqNumFlag=Y, resetting sequence numbers to 1
20190612-16:56:24: Received logon
